project:
  type: website
  output-dir: docs
website:
  title: "Big Data Finance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles/styles.css
    toc: true



